resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=error
      - FEATURE_X=false
secretGenerator:
  - name: app-secret
    literals:
      - DB_PASSWORD=prodpassword
      - API_KEY=prodkey
